nft_dapp:
  data: fift/dapp-data.fif
  func:
    - func/nft-dapp.func
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func

nft_collection:
  data: fift/collection-data.fif
  func:
    - func/nft-collection.func
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func
  tests:
    - tests/collection-tests.func
    - tests/collection-tests-int.func

nft:
  data: fift/item-data.fif
  func:
    - func/nft-item.func
    - func/utils/helpers.func
    - func/utils/params.func
    - func/utils/op-codes.func
  tests:
    - tests/nft-tests.func
    - tests/nft-tests-int.func
